# Generated by Django 2.1 on 2018-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p7user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.Permission'),
        ),
    ]
