# Generated by Django 2.1 on 2018-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0002_p7user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='p7user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.Group'),
        ),
    ]
