"""
Django settings for project_7 project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@^5abv&l*_)^swykr5itnt@5ud%n5llgj(!37w-g1nq2m5e03w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_7.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 14,
        }
    },
    {
        'NAME': 'users.forms.NumericValidator',
    },
    {
        'NAME': 'users.forms.LowerCaseValidator',
    },
    {
        'NAME': 'users.forms.UpperCaseValidator',
    },
    {
        'NAME': 'users.forms.SpecialCharacterValidator',
    },
    {
        'NAME': 'users.forms.OtherIdentityAttributesValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
]

# Media files (user images, etc)
# https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-MEDIA_ROOT
MEDIA_ROOT = os.path.join(
    BASE_DIR,
    'public',
    'media'    
)
MEDIA_URL = '/public/media/'

# Email settings (for production)
# (comment out the File backend section if using)
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # This is the default so does not need to be explicitly set
EMAIL_HOST =  # host IP
EMAIL_PORT =  # host port
EMAIL_HOST_USER =  # host username
EMAIL_HOST_PASSWORD =  # host password
EMAIL_USE_TLS =
EMAIL_USE_SSL =
EMAIL_TIMEOUT = # if not set this uses socket.getdefaulttimeout which has default of None
EMAIL_SSL_KEYFILE = 
EMAIL_SSL_CERTIFICATE =
"""

# File backend (for testing only)
# (comment out the Email settings section if using)
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend' # Only for testing!
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'debug_files', 'emails', 'forgot_password')


AUTH_USER_MODEL = 'users.P7User'

# Default is to go to `accounts/profile`
LOGIN_REDIRECT_URL = reverse_lazy('home')
